[pytest]
markers =
    atm: Tests related to the ATM hardware logic.
    account: Tests related to user accounts and balances.
    admin: Tests related to Administration privileges.
    technician: Tests related to Technician maintenance.

